### ISSUE TITLE
mybatis-column-data-encryption maven包无法加载

### ISSUE THREAD

**Issue by lvwei82604532** [ColinZou/mybatis-column-encryption#2]
您好，mybatis-column-encryption中的example pom文件mybatis-column-data-encryption包无法下载。

**Comment by ColinZou** [comment]
您好，可能是由于这个仓库需要科学上网的原因，你可以尝试直接拉取代码，然后执行 mvn install以后引用该依赖。

**Comment by lvwei82604532** [comment]
<dependency>
    <groupId>com.stableforever</groupId>
    <artifactId>mybatis-column-data-encryption</artifactId>
    <version>0.0.1</version>
</dependency>

md文档上有错误，应该是上述引入。 version = 0.0.1
