### ISSUE TITLE
example 代码跑不通 Given final block not properly padded. Such issues can arise if a bad key is used during decrypt

### ISSUE THREAD

**Issue by lvwei82604532** [ColinZou/mybatis-column-encryption#3]
![image](https://user-images.githubusercontent.com/43466888/79096792-a7ab3780-7d90-11ea-8315-5c1cace7adac.png)

example启动后出现上图异常。

**Comment by ColinZou** [comment]
样本代码应用了AES 256，需要你在JDK上做设置，启用Unlimited Strength：
https://www.jianshu.com/p/de81059a9e97
下载地址：
https://www.oracle.com/java/technologies/javase-jce-all-downloads.html
